### ISSUE TITLE
Fabric API changed, now it's crashing

### ISSUE THREAD

**Issue by pkmnfrk** [Lemonszz/SimpleTeleporters#21]
```
[12:42:56] [main/INFO]: [MixinLoader] Loading 3 mods: fabricloader(0.3.7), fabric(0.2.3), simpleteleporters(1.0.0)
[12:42:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/G:/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.16/sponge-mixin-0.7.11.16.jar Service=Knot/Fabric Env=CLIENT
[12:42:56] [main/INFO]: Compatibility level set to JAVA_8
[12:42:57] [main/INFO]: Setting user: pkmnfrk
[12:43:01] [main/INFO]: [FabricLoader] Loading 3 mods: fabricloader(0.3.7), fabric(0.2.3), simpleteleporters(1.0.0)
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 26/02/19 12:43 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/fabricmc/fabric/block/FabricBlockSettings
	at party.lemons.simpleteleporters.init.SimpleTeleportersBlocks.init(SimpleTeleportersBlocks.java:20)
	at party.lemons.simpleteleporters.SimpleTeleporters.onInitialize(SimpleTeleporters.java:20)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.class_310.handler$init$zzb000(class_310.java:2488)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:397)
       <useless stacktrace omitted>
```

I believe the `net.fabricmc.fabric.block` package moved to `net.fabricmc.fabric.api.block`

**Comment by insanj** [comment]
👍 Also having issues running the mod at all in the latest snapshots. I've begun to work on a PR on the appropriate repo (https://github.com/Lemonszz/SimpleTeleporters-Fabric), but I ran into some tricky API changes. Will keep working on it and try to get an update before a week or two.

**Comment by insanj** [comment]
@pkmnfrk This has been fixed and pushed as of the weekend. Issue should be closed!
